# Markdownlint configuration for RHCE study repository
# Tailored for technical documentation and study materials

# Default rules with customizations
default: true

# Line length - allow longer lines for code examples and URLs
MD013:
  line_length: 120
  heading_line_length: 80
  code_blocks: false
  tables: false
  headers: true
  stern: false

# Allow multiple spaces after list markers for alignment
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Allow inline HTML for complex tables and formatting
MD033: false

# Allow bare URLs in documentation
MD034: false

# Don't require language specification for code fences in examples
MD040: false

# Don't enforce first line as H1 (allow flexibility in page structure)
MD041: false

# Allow emphasis markers for technical terms
MD036: false

# Disable dollar signs in math mode (conflicts with shell examples)
MD044: false