site_name: RHCE Certification Study Guide
site_description: Comprehensive study materials and resources for Red Hat Certified Engineer (RHCE) exam preparation with focus on Ansible automation
site_author: RHCE Study Repository
site_url: https://kraker.github.io/rhce/

# Repository information
repo_name: kraker/rhce
repo_url: https://github.com/kraker/rhce
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - shell
    - yaml
    - ini
    - json

# Navigation structure
nav:
  - Home: index.md
  - Study Modules:
    - Overview: rhce_synthesis/index.md
    - 'Module 00: Exam Overview': rhce_synthesis/00_exam_overview.md
    - 'Module 01: Ansible Basics': rhce_synthesis/01_ansible_basics.md
    - 'Module 02: Playbooks & Tasks': rhce_synthesis/02_playbooks_tasks.md
    - 'Module 03: Variables & Facts': rhce_synthesis/03_variables_facts.md
    - 'Module 04: Task Control': rhce_synthesis/04_task_control.md
    - 'Module 05: Templates': rhce_synthesis/05_templates.md
    - 'Module 06: Roles': rhce_synthesis/06_roles.md
    - 'Module 07: Ansible Vault': rhce_synthesis/07_ansible_vault.md
    - 'Module 08: Advanced Features': rhce_synthesis/08_advanced_features.md
  - Quick References:
    - 'Exam Quick Reference': exam_quick_reference.md
    - 'Ansible Module Reference': ansible_module_reference.md
    - 'Command Reference': command_reference.md
    - 'RHCE Glossary': rhce_glossary.md

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - tables

# Extra configuration
extra:
  generator: false
  
# Copyright information  
copyright: 'Study materials for RHCE certification preparation'

# Build directory
site_dir: site

# Exclude template files from build
exclude_docs: |
  rhce_synthesis/_template.md