---
# Configure control nodes

- name: Configure control nodes
  hosts: control
  become: true
  tasks:
    # ansible-automation-platform (AAP) provides things like ansible-builder,
    # ansible-navigator, etc.
    # List Repo IDs:
    #   subscription-manager repos --list | grep ansible-automation-platform
    - name: Enable ansible-automation-platform repository
      community.general.rhsm_repository:
        name: ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms

    - name: Install Ansible packages
      ansible.builtin.dnf:
        name:
          - ansible
          - ansible-builder
          - ansible-navigator
        state: present

    - name: Install common dependencies
      ansible.builtin.dnf:
        name:
          - container-tools  # meta package that provides podman, skopeo, etc.
        state: present

    - name: Install Ansible inventory
      ansible.builtin.copy:
        content: |
          # RHCE Lab Inventory

          [control]
          control1

          [managed]
          ansible1
          ansible2
          ansible3
          ansible4

          [all:vars]
          ansible_user=ansible
          ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        dest: /etc/ansible/hosts
        backup: true
        owner: root
        group: ansible
        mode: "0664"

    - name: Create SSH key for ansible user
      ansible.builtin.user:
        name: ansible
        generate_ssh_key: true
        ssh_key_type: rsa
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Read the public key for distribution
      ansible.builtin.slurp:
        src: /home/ansible/.ssh/id_rsa.pub
      register: ansible_public_key
      run_once: true

    - name: Store public key as fact
      ansible.builtin.set_fact:
        ansible_pubkey_content: "{{ ansible_public_key.content | b64decode | trim }}"
      run_once: true
