---
# Master playbook for RHCE lab environment

- name: Configure all hosts with common settings
  hosts: all
  become: true
  tasks:
    # Skip package updates to avoid EPEL conflicts in lab environment
    # - name: Update packages (not latest to avoid EPEL issues)
    #   ansible.builtin.dnf:
    #     name: '*'
    #     state: present
    #     update_cache: true

    - name: Install essential packages
      ansible.builtin.dnf:
        name:
          - vim
          - wget
          - curl
          - tree
          - git
          - bash-completion
          - python3-pip
        state: present

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        comment: "Ansible automation user"
        shell: /bin/bash
        create_home: true
        groups: wheel
        append: true

    # Update this to sudoers module?
    - name: Set up passwordless sudo for ansible user
      ansible.builtin.copy:
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ansible
        mode: '0440'
        validate: 'visudo -cf %s'

    # Is there a module for managing hosts file?
    - name: Configure /etc/hosts for all lab VMs
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          # RHCE Lab VMs
          192.168.4.200 control1.example.com control1
          192.168.4.201 ansible1.example.com ansible1
          192.168.4.202 ansible2.example.com ansible2
          192.168.4.203 ansible3.example.com ansible3
          192.168.4.204 ansible4.example.com ansible4
        marker: "# {mark} RHCE LAB HOSTS"

- name: Control
  ansible.builtin.import_playbook: control.yml

- name: Managed
  ansible.builtin.import_playbook: managed.yml
