---
# Master playbook for RHCE lab environment

- name: Configure all hosts with common settings
  hosts: all
  become: true
  tasks:
    # EPEL is not officially supported and therefore won't be on the exam.
    - name: Uninstall EPEL
      ansible.builtin.dnf:
        name: epel-release
        state: absent

    - name: Update packages  # noqa package-latest
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
      notify: Reboot  # Reboot after system updates

    # Consider removing?
    - name: Install essential packages
      ansible.builtin.dnf:
        name:
          - vim
          - wget
          - curl
          - tree
          - git
          - bash-completion
          - python3-pip
        state: present

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        comment: "Ansible automation user"
        shell: /bin/bash
        create_home: true
        groups: wheel
        append: true

    # Update this to sudoers module?
    - name: Set up passwordless sudo for ansible user
      ansible.builtin.copy:
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ansible
        mode: '0440'
        validate: 'visudo -cf %s'

    # Is there a module for managing hosts file?
    # Answer: There isn't, but there is win_hosts for managing the Windows hosts
    # file...
    - name: Configure /etc/hosts for all lab VMs
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          # RHCE Lab VMs
          192.168.4.200 control1.example.com control1
          192.168.4.201 ansible1.example.com ansible1
          192.168.4.202 ansible2.example.com ansible2
          192.168.4.203 ansible3.example.com ansible3
          192.168.4.204 ansible4.example.com ansible4
        marker: "# {mark} RHCE LAB HOSTS"

  handlers:
    - name: Reboot
      ansible.builtin.reboot:

- name: Control
  ansible.builtin.import_playbook: control.yml

- name: Managed
  ansible.builtin.import_playbook: managed.yml
